- hosts: localhost
  become: true
  pre_tasks:
    - name: Updating repositories
      dnf:
        name: "*"
        state: latest
      tags: ['dev']

  tasks:
    - name: Removing unnecessary packages
      dnf:
        name:
          - akregator
          - dnfdragora
          - dragon
          - kaddressbook
          - kamoso
          - kcalc
          - kcharselect
          - kde-connect
          - kde-partitionmanager
          - kfind
          - kgpg
          - kmag
          - kmahjongg
          - kmail
          - kmines
          - kmousetool
          - kmouth
          - kolourpaint
          - kontact
          - konversation
          - korganizer
          - kpat
          - krdc
          - krfb
          - kwrite
          - plasma-discover
        state: absent
        autoremove: yes
      tags: ['setup']

    - name: Installing fonts
      dnf:
        name:
          - ibm-plex-fonts-all
        state: latest
      tags: ['dev']

    - name: Installing apps
      dnf:
        name:
          - kate
          - thunderbird
          - qbittorrent
      tags: ['setup']

    - name: Installing development tools
      dnf:
        name:
          - fzf
          - git
          - neovim
          - pipenv
          - ripgrep
          - starship
          - stow
          - tmux
          - trash-cli
          - zola
        state: latest
      tags: ['dev']
